export const list = [
    'I hate it when I go to hug someone really sexy and my face smashes right into the mirror.',
    'Not all men are annoying. Some are dead.',
    'If you’re here, who’s running hell?',
    'I swear I wasn’t lying, I was just writing fiction with my mouth again.',
    'Would you like to dance? No? You must’ve misheard me. I said you look fat in those pants.',
    'I can totally keep secrets. It’s the people I tell them to who can’t.',
    'Did you fall from heaven? Cause your face looks kind of funky.',
    'If I promise to miss you, will you go, like, really far away?',
    'Don’t you hate people who use big words just to make themselves look perspicacious?',
    'Take my advice — it’s not like I’m dumb enough to.',
    'Light travels faster than sound, which is why people like you appear bright—until they open their mouths. ',
    'Did something bad happen to you, or are you just naturally this terrible of a person?',
    'If at first you don’t succeed, stop trying already. You’re probably dumb.',
    'My son asked me what it’s like to be married so I told him to leave me. When he did, I asked why he was ignoring me.',
    'You might love your life, but I think it just wants to be friends.',
    'I always tell new hires, “Don’t think of me as your boss, think of me as a friend who can fire you.”',
    'Why is it that everything you love is either unhealthy, addictive, or has multiple restraining orders against you?',
    'When I see ads on TV featuring smiley housewives using some new cleaning product, the only thing I want to buy are the meds they’re clearly on.',
    'Those of you who think you know it all are really annoying to those of us who do.',
    'Well, this day was a total waste of makeup.',
    'Hear that? It’s the sound of you not talking for once.',
    'I’m pretty sure I married someone else’s soulmate. If only they’d come around and take him off my hands.',
    'My girlfriend told me to go out and get something that makes her look sexy, so I got drunk.',
    'Why do people make end-of-the-world jokes like there’s no tomorrow?',
    'Your opinion is very important to me. Please stay on the line until you hear the beep for voicemail.',
    'Hi there, I’m human. What are you?',
    'Always remember: You’re just as unique as everybody else.',
    'Strong people don’t put others down. They lift them up and slam them on the ground.',
    'I would kill for a Nobel Peace Prize.',
    'Tell me what you need, and I’ll tell you how to get along without it since you’re not that bright.',
    'If at first you don’t succeed, blame someone else and seek counseling.',
    'Please tell me this train of thought you’re on has a caboose.',
    'Even people who are good for nothing can bring a smile to your face—once you shove them down the stairs, that is.',
    'If you see me smiling it’s because I’m thinking of doing something bad. If you see me laughing, it’s because I already have.',
    'The sooner I shoot you, the sooner I’ll get out of jail for it. Don’t assume that’s not a major incentive.',
    'This obviously isn’t working out. I think it’s time for us to go our separate ways and start making other people miserable.',
    'If you need so much space, there’s always NASA.',
    'They say you are what you eat, so lay off the nuts already.',
    'Your mind might want to dance, but your body is a really awkward white guy.',
    'I didn’t say it was your fault, I said I was blaming you.',
    'Sorry, my dog ate your text again.',
    'Would you rather have a million bucks, or [insert name]’s head full of nickels?',
    'Oh, I didn’t tell you? Must be none of your business then.',
    'So many freaks, so few circuses.',
    'If idiots grew on trees, this place would be an orchard.',
    'I have as much authority as the Pope. There just aren’t as many people who believe it.',
    'Honesty may be the best policy, but insanity is the best defense.',
    'I’d be fine if there weren’t so much blood in my alcohol system.',
    'Masturbation is like procrastination—it’s all good fun until you realize you’re just fucking yourself.',
    'Think I’m sarcastic? Watch me pretend to care. ',
    'My girlfriend was complaining last night that I never listen to her. Or something like that... ',
    'I hope when I inevitably choke to death on gummy bears people just say I was killed by bears and leave it at that. ',
    'I tried to explain to my 4-year-old son that it\'s perfectly normal to accidentally poop your pants, but he\'s still making fun of me.',
    'Being an adult is just walking around wondering what you\'re forgetting. ',
    'Apparently I snore so loudly that it scares everyone in the car I\'m driving. ',
    'What\'s worse than raining cats and dogs? Hailing Taxi.',
    'To this day, the boy that used to bully me at school still takes my lunch money. On the plus side, he makes great Subway sandwiches. ',
    'If at first you don\'t succeed, we have a lot in common. ',
    'Last night in my dream I was peeing in bed. Dreams do come true I realized in the morning. ',
    'When I told the doctor about my loss of memory, he made me pay in advance. ',
    'Don\'t you hate it when someone answers their own questions? I do. ',
    'Diet Day #1 - I removed all the fattening food from my house. It was delicious. ',
    'Why is the day that you do laundry, cook, clean, iron and so on, called a day off? ',
    'I didn\'t say it was your fault, I said I was blaming you. ',
    'Girl you\'re like a car accident, cause I just can\'t look away.',
    'I named my dog 6 miles so I can tell people that I walk 6 miles every single day. ',
    'For maximum attention, nothing beats a good mistake.',
    'I can totally keep secrets. It\'s the people I tell them to that can\'t.',
    'Strong people don\'t put others down. They lift them up and slam them on the ground for maximum damage.',
    'A clean desk is a sign of a cluttered desk drawer.'
];

export const THEME = {
    'UNITED': 'https://bootswatch.com/4/united/bootstrap.min.css',
    'DARK': 'https://bootswatch.com/4/darkly/bootstrap.min.css'
};
export const URL = {
    'DAD': 'https://icanhazdadjoke.com/',
    'CN': 'https://api.chucknorris.io/jokes/random',
    'APP': 'www.google.com'
};

